- import_tasks: install.yml
- import_tasks: configure.yml

- block:
  - name: Verifying installation of MariaDB
    shell: mysql --version
    register: mysql_version

  - debug:
      msg="{{ mysql_version }}"

- block:
  - name: Verifying if MariaDB is started and running in the background
    shell: systemctl status mariadb
    register: mariadb_service

  - debug:
      msg="{{ mariadb_service }}"
